// examples/sveltekit/src/routes/drafts/+page.svelte
<script lang="ts">
  import type { ActionData, PageData } from './$types'
  import { enhance } from '$app/forms'

  let { data, form }: { data: PageData, form: ActionData } = $props()
</script>

<h1>Drafts</h1>
<p><code>{data.space}</code></p>
{#if form?.message}<p>{form.message}</p>{/if}

<form method="POST" action="?/create" enctype="multipart/form-data" use:enhance>
  <p><input name="title" placeholder="Title" required /></p>
  <p><textarea name="body" placeholder="# Markdown body"></textarea></p>
  <p>
    <select name="tag">
      <option value="">no tag</option>
      {#each data.tags as tag (tag.rkey)}<option value={tag.rkey}>{tag.name}</option>{/each}
    </select>
    <input name="newTag" placeholder="or a new tag" />
  </p>
  <p><input type="file" name="cover" accept="image/*" /></p>
  <button type="submit">Create draft</button>
</form>

{#each data.drafts as draft (draft.uri)}
  <article>
    <h2>{draft.value.title}</h2>
    {#if draft.published}
      <p>published</p>
    {:else}
      <form method="POST" action="?/publish" use:enhance>
        <input type="hidden" name="rkey" value={draft.rkey} />
        <button type="submit">Publish</button>
      </form>
    {/if}
  </article>
{/each}

// examples/nuxt/app/pages/drafts.vue
<script setup lang="ts">
const { data, refresh } = await useFetch('/api/drafts')
const form = ref<HTMLFormElement>()

async function create() {
  await $fetch('/api/drafts', { method: 'POST', body: new FormData(form.value!) })
  form.value!.reset()
  await refresh()
}

async function publish(rkey: string) {
  await $fetch(`/api/drafts/${rkey}/publish`, { method: 'POST' })
  await refresh()
}
</script>

<template>
  <div v-if="data">
    <h1>Drafts</h1>
    <form ref="form" @submit.prevent="create">
      <p><input name="title" placeholder="Title" required></p>
      <p><textarea name="body" placeholder="# Markdown body" /></p>
      <p>
        <select name="tag">
          <option value="">
            no tag
          </option>
          <option v-for="tag in data.tags" :key="tag.rkey" :value="tag.rkey">
            {{ tag.name }}
          </option>
        </select>
        <input name="newTag" placeholder="or a new tag">
      </p>
      <p><input type="file" name="cover" accept="image/*"></p>
      <button type="submit">
        Create draft
      </button>
    </form>

    <article v-for="draft in data.drafts" :key="draft.uri">
      <h2>{{ draft.value.title }}</h2>
      <p v-if="draft.published">
        published
      </p>
      <button v-else @click="publish(draft.rkey)">
        Publish
      </button>
    </article>
  </div>
</template>
